"""all_tables2

Revision ID: 9b5647bc12e6
Revises: e72623e43bf8
Create Date: 2026-09-30 13:20:42.693235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel column types (e.g. sqlmodel.sql.sqltypes.AutoString)
                 # show up in autogenerated ops without this import ever being
                 # added automatically - without it, every migration touching
                 # a string column raises NameError the moment it actually runs.


# revision identifiers, used by Alembic.
revision: str = '9b5647bc12e6'
down_revision: Union[str, None] = 'e72623e43bf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_users_round_up_vault_id', 'users', 'vaults', ['round_up_vault_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_round_up_vault_id', 'users', type_='foreignkey')
    # ### end Alembic commands ###
