"""all_tables

Revision ID: e72623e43bf8
Revises: 
Create Date: 2026-09-30 12:38:26.446458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel column types (e.g. sqlmodel.sql.sqltypes.AutoString)
                 # show up in autogenerated ops without this import ever being
                 # added automatically - without it, every migration touching
                 # a string column raises NameError the moment it actually runs.


# revision identifiers, used by Alembic.
revision: str = 'e72623e43bf8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_phone_verified', sa.Boolean(), nullable=False),
    sa.Column('kyc_tier', sa.Enum('UNVERIFIED', 'PHONE_VERIFIED', 'ID_VERIFIED', name='kyc_tier'), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sender_profile', sa.JSON(), nullable=True),
    sa.Column('referral_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('referred_by_id', sa.Uuid(), nullable=True),
    sa.Column('referral_reward_status', sa.Enum('NONE', 'PENDING', 'REWARDED', name='referral_reward_status'), nullable=False),
    sa.Column('default_momo_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('default_momo_bank_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('default_account_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('round_up_vault_id', sa.Uuid(), nullable=True),
    sa.Column('round_up_denomination', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('paystack_authorization_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('paystack_card_last4', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['referred_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['round_up_vault_id'], ['vaults.id'], name='fk_users_round_up_vault_id', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('admin_user_id', sa.Uuid(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seq')
    )
    op.create_index(op.f('ix_admin_audit_logs_admin_user_id'), 'admin_audit_logs', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_target_id'), 'admin_audit_logs', ['target_id'], unique=False)
    op.create_table('crossborder_transfers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('source_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('destination_country', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('destination_currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('destination_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('exchange_rate_used', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('from_asset', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quote_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bitnob_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('beneficiary_details', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_PAYMENT', 'PROCESSING', 'COMPLETED', 'FAILED', 'DELIVERY_FAILED', 'REFUND_PENDING', 'REFUNDED', name='crossborder_status'), nullable=False),
    sa.Column('payment_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bitnob_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('failure_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('refund_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crossborder_transfers_payment_reference'), 'crossborder_transfers', ['payment_reference'], unique=False)
    op.create_index(op.f('ix_crossborder_transfers_sender_id'), 'crossborder_transfers', ['sender_id'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('response_body', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', 'endpoint', name='uq_idempotency_key_scope')
    )
    op.create_index(op.f('ix_idempotency_keys_user_id'), 'idempotency_keys', ['user_id'], unique=False)
    op.create_table('otps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.Enum('PASSWORD_RESET', 'PHONE_VERIFICATION', name='otp_purpose'), nullable=False),
    sa.Column('code_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otps_user_id'), 'otps', ['user_id'], unique=False)
    op.create_table('split_bills',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organizer_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'SETTLED', 'CANCELLED', 'WITHDRAWN', name='split_bill_status'), nullable=False),
    sa.Column('collects_funds', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_split_bills_organizer_id'), 'split_bills', ['organizer_id'], unique=False)
    op.create_table('transaction_volume_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_volume_logs_user_id'), 'transaction_volume_logs', ['user_id'], unique=False)
    op.create_table('vaults',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('contribution_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='vaultfrequency'), nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('lock_until', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'MATURED', 'WITHDRAWN', 'CANCELLED', name='vaultstatus'), nullable=False),
    sa.Column('recurring_status', sa.Enum('INACTIVE', 'ACTIVE', 'PAUSED', 'SUSPENDED', name='vault_recurring_status'), nullable=False),
    sa.Column('next_charge_date', sa.Date(), nullable=True),
    sa.Column('recurring_consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('recurring_last_failure_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vaults_owner_id'), 'vaults', ['owner_id'], unique=False)
    op.create_table('virtual_cards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('bitnob_card_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bitnob_customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PENDING_PAYMENT', 'PROVISIONING', 'ACTIVE', 'FROZEN', 'TERMINATED', 'FAILED', 'DELIVERY_FAILED', 'REFUND_PENDING', 'REFUNDED', name='virtual_card_status'), nullable=False),
    sa.Column('masked_pan', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('card_brand', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('initial_funding_ghs', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fee_ghs', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('failure_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dial_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('local_phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('refund_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('termination_refund_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('termination_payout_ghs', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('termination_payout_status', sa.Enum('NOT_STARTED', 'NOT_NEEDED', 'PENDING', 'COMPLETED', 'FAILED', name='card_termination_payout_status'), nullable=False),
    sa.Column('termination_payout_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('decline_strikes', sa.Integer(), nullable=False),
    sa.Column('decline_fees_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('last_decline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_virtual_cards_payment_reference'), 'virtual_cards', ['payment_reference'], unique=False)
    op.create_index(op.f('ix_virtual_cards_termination_payout_reference'), 'virtual_cards', ['termination_payout_reference'], unique=False)
    op.create_index(op.f('ix_virtual_cards_user_id'), 'virtual_cards', ['user_id'], unique=False)
    op.create_table('wallet_transfers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_id', sa.Uuid(), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('roundup_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING_PAYMENT', 'AWAITING_RECIPIENT_PAYOUT_INFO', 'PAYOUT_PENDING', 'COMPLETED', 'FAILED', name='transferstatus'), nullable=False),
    sa.Column('payment_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('authorization_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payout_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_transfers_payment_reference'), 'wallet_transfers', ['payment_reference'], unique=False)
    op.create_index(op.f('ix_wallet_transfers_recipient_id'), 'wallet_transfers', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_wallet_transfers_sender_id'), 'wallet_transfers', ['sender_id'], unique=False)
    op.create_table('card_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('card_id', sa.Uuid(), nullable=True),
    sa.Column('bitnob_card_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amount_usd', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('merchant', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['virtual_cards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', name='uq_card_events_event_id')
    )
    op.create_index(op.f('ix_card_events_bitnob_card_id'), 'card_events', ['bitnob_card_id'], unique=False)
    op.create_index(op.f('ix_card_events_card_id'), 'card_events', ['card_id'], unique=False)
    op.create_index(op.f('ix_card_events_event_id'), 'card_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_card_events_event_type'), 'card_events', ['event_type'], unique=False)
    op.create_table('split_bill_shares',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('split_bill_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'CANCELLED', name='split_bill_share_status'), nullable=False),
    sa.Column('payment_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payout_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payout_status', sa.Enum('NOT_STARTED', 'PENDING', 'COMPLETED', 'FAILED', name='split_bill_share_payout_status'), nullable=False),
    sa.Column('refund_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['split_bill_id'], ['split_bills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_split_bill_shares_payment_reference'), 'split_bill_shares', ['payment_reference'], unique=False)
    op.create_index(op.f('ix_split_bill_shares_split_bill_id'), 'split_bill_shares', ['split_bill_id'], unique=False)
    op.create_index(op.f('ix_split_bill_shares_user_id'), 'split_bill_shares', ['user_id'], unique=False)
    op.create_table('split_bill_withdrawals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('split_bill_id', sa.Uuid(), nullable=False),
    sa.Column('destination', sa.Enum('MOMO', 'VAULT', name='split_withdrawal_destination'), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='split_withdrawal_status'), nullable=False),
    sa.Column('payout_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('failure_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['split_bill_id'], ['split_bills.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_split_bill_withdrawals_payout_reference'), 'split_bill_withdrawals', ['payout_reference'], unique=False)
    op.create_index(op.f('ix_split_bill_withdrawals_split_bill_id'), 'split_bill_withdrawals', ['split_bill_id'], unique=True)
    op.create_table('vault_contributions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'FAILED', name='vault_contribution_status'), nullable=False),
    sa.Column('payment_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vault_contributions_payment_reference'), 'vault_contributions', ['payment_reference'], unique=False)
    op.create_index(op.f('ix_vault_contributions_vault_id'), 'vault_contributions', ['vault_id'], unique=False)
    op.create_table('vault_withdrawals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='withdrawalstatus'), nullable=False),
    sa.Column('payout_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vault_withdrawals_vault_id'), 'vault_withdrawals', ['vault_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vault_withdrawals_vault_id'), table_name='vault_withdrawals')
    op.drop_table('vault_withdrawals')
    op.drop_index(op.f('ix_vault_contributions_vault_id'), table_name='vault_contributions')
    op.drop_index(op.f('ix_vault_contributions_payment_reference'), table_name='vault_contributions')
    op.drop_table('vault_contributions')
    op.drop_index(op.f('ix_split_bill_withdrawals_split_bill_id'), table_name='split_bill_withdrawals')
    op.drop_index(op.f('ix_split_bill_withdrawals_payout_reference'), table_name='split_bill_withdrawals')
    op.drop_table('split_bill_withdrawals')
    op.drop_index(op.f('ix_split_bill_shares_user_id'), table_name='split_bill_shares')
    op.drop_index(op.f('ix_split_bill_shares_split_bill_id'), table_name='split_bill_shares')
    op.drop_index(op.f('ix_split_bill_shares_payment_reference'), table_name='split_bill_shares')
    op.drop_table('split_bill_shares')
    op.drop_index(op.f('ix_card_events_event_type'), table_name='card_events')
    op.drop_index(op.f('ix_card_events_event_id'), table_name='card_events')
    op.drop_index(op.f('ix_card_events_card_id'), table_name='card_events')
    op.drop_index(op.f('ix_card_events_bitnob_card_id'), table_name='card_events')
    op.drop_table('card_events')
    op.drop_index(op.f('ix_wallet_transfers_sender_id'), table_name='wallet_transfers')
    op.drop_index(op.f('ix_wallet_transfers_recipient_id'), table_name='wallet_transfers')
    op.drop_index(op.f('ix_wallet_transfers_payment_reference'), table_name='wallet_transfers')
    op.drop_table('wallet_transfers')
    op.drop_index(op.f('ix_virtual_cards_user_id'), table_name='virtual_cards')
    op.drop_index(op.f('ix_virtual_cards_termination_payout_reference'), table_name='virtual_cards')
    op.drop_index(op.f('ix_virtual_cards_payment_reference'), table_name='virtual_cards')
    op.drop_table('virtual_cards')
    op.drop_index(op.f('ix_vaults_owner_id'), table_name='vaults')
    op.drop_table('vaults')
    op.drop_index(op.f('ix_transaction_volume_logs_user_id'), table_name='transaction_volume_logs')
    op.drop_table('transaction_volume_logs')
    op.drop_index(op.f('ix_split_bills_organizer_id'), table_name='split_bills')
    op.drop_table('split_bills')
    op.drop_index(op.f('ix_otps_user_id'), table_name='otps')
    op.drop_table('otps')
    op.drop_index(op.f('ix_idempotency_keys_user_id'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('ix_crossborder_transfers_sender_id'), table_name='crossborder_transfers')
    op.drop_index(op.f('ix_crossborder_transfers_payment_reference'), table_name='crossborder_transfers')
    op.drop_table('crossborder_transfers')
    op.drop_index(op.f('ix_admin_audit_logs_target_id'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_admin_user_id'), table_name='admin_audit_logs')
    op.drop_table('admin_audit_logs')
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
